# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rk3588-custom"
BBFILE_PATTERN_rk3588-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_rk3588-custom = "10"

LAYERDEPENDS_rk3588-custom = "core rockchip rockchip-updateimg"
LAYERSERIES_COMPAT_rk3588-custom = "scarthgap"
